DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(150) NOT NULL,
    email           VARCHAR(150)  NOT NULL,
    CONSTRAINT      pk_user PRIMARY KEY (id),
    CONSTRAINT      UQ_USER_EMAIL UNIQUE (email)
);

DROP TABLE IF EXISTS requests CASCADE;
CREATE TABLE requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description     CHARACTER VARYING(150),
    user_id         INTEGER,
    date_create     DATE,
    CONSTRAINT      REQUESTS_PK PRIMARY KEY (id),
    CONSTRAINT      CONSTRAINT_REQUESTS_USER_ID FOREIGN KEY (user_id) REFERENCES USERS (id)
);

DROP TABLE IF EXISTS items CASCADE;
CREATE TABLE items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            CHARACTER VARYING(150) NOT NULL,
    description     CHARACTER VARYING(150) NOT NULL,
    is_available    BOOLEAN DEFAULT FALSE NOT NULL,
    request_id      INTEGER,
    user_id         INTEGER,
    CONSTRAINT      ITEMS_PK PRIMARY KEY (id),
    CONSTRAINT      CONSTRAINT_ITEMS_REQUEST_ID FOREIGN KEY (request_id) REFERENCES REQUESTS (id) on delete cascade on update cascade,
    CONSTRAINT      CONSTRAINT_ITEMS_USER_ID FOREIGN KEY (user_id) REFERENCES USERS (id) on delete cascade on update cascade
);

CREATE TABLE IF NOT EXISTS BOOKING (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_begin      TIMESTAMP,
    date_end        TIMESTAMP,
    user_id         INTEGER,
    item_id         INTEGER,
    status          CHARACTER VARYING(150),
    CONSTRAINT      BOOKING_PK PRIMARY KEY (id),
    CONSTRAINT      CONSTRAINT_BOOKING_USER_ID FOREIGN KEY (user_id) REFERENCES USERS (id) on delete cascade on update cascade,
    CONSTRAINT      CONSTRAINT_BOOKING_ITEM_ID FOREIGN KEY (item_id) REFERENCES ITEMS (id) on delete cascade on update cascade
);

CREATE TABLE IF NOT EXISTS COMMENTS (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text            CHARACTER VARYING(150),
    user_id         INTEGER,
    item_id         INTEGER,
    date_created    TIMESTAMP,
    CONSTRAINT      COMMENTS_PK PRIMARY KEY (id),
    CONSTRAINT      CONSTRAINT_COMMENTS_USER_ID FOREIGN KEY (user_id) REFERENCES USERS (id) on delete cascade on update cascade,
    CONSTRAINT      CONSTRAINT_COMMENTS_ITEM_ID FOREIGN KEY (item_id) REFERENCES ITEMS (id) on delete cascade on update cascade
);